# Compute resource metrics on a regular interval and
# report the metrics to Application Insights

FROM resin/raspberrypi3-python:3.6-wheezy

LABEL maintainer="Daniel Grooms, daniel.grooms@careotter.com"

WORKDIR /app

RUN pip install applicationinsights psutil

COPY ./src/ ./

# Usually you should map "/proc" to "/host/proc" and "/" to "/host/dir"
VOLUME [ "/host/proc", "/host/dir" ]

ENTRYPOINT [ "python", "./program.py" ]
